### ISSUE TITLE
Cannot download 'detecting-insults-in-social-commentary' data due to the 'late submission' button on Kaggle grey

### ISSUE THREAD

**Issue by jessyford** [openai/mle-bench#14]
The prepare program of mlebench requires me to accpet the competition rules of 'detecting-insults-in-social-commentary' on Kaggle.

However the late submission button on Kaggle of 'detecting-insults-in-social-commentary' is grey and cannot be clicked.

Do you have any ideas? Thank you.

<img width="1296" alt="buttongrey" src="https://github.com/user-attachments/assets/3570bc83-dfb4-4152-8fc8-467387ac0724">

**Comment by thesofakillers** [comment]
Hi. That's not the button to press, you should navigate to the "Rules" tab of the competition and accept the rules with the "Join Competition" button at the bottom.

**Comment by thesofakillers** [comment]
thank you for flagging! Pretty strange, will look into it

**Comment by thesofakillers** [comment]
have you verified your Kaggle account?

**Comment by jessyford** [comment]
> have you verified your Kaggle account?

Yes, I have verified my identity using Persona, and my phone as well.

Besides, I just found one more grey-button competition: the-icml-2013-whale-challenge-right-whale-redux
<img width="1249" alt="buttongrey2" src="https://github.com/user-attachments/assets/58c8a541-956c-41e2-b741-cd8da507ae2b">

**Comment by jessyford** [comment]
> Could you try accepting the rules via the Data tab as shown in this video?
> 
>  Detecting.Insults.in.Social.Commentary._.Kaggle.-.21.October.2024.mp4

Cool! All three competitions(detecting-insults-in-social-commentary,the-icml-2013-whale-challenge-right-whale-redux,playground-series-s3e18) with grey late-submission button can be accessed by clicking the join competition button in this way. Thank you so much :)

**Comment by james-aung** [comment]
Great! Agreed that this is somewhat confusing.
