### ISSUE TITLE
How to change OPENAI_API_BASE and used LLM

### ISSUE THREAD

**Issue by XingYing-stack** [openai/mle-bench#23]
Thank you for your very impressive work, I want to run a sample using AIDE framework, where I want to change OPENAI_API_BASE and the specific LLM to run like using GPT-4o-mini, but unfortunately, I tried changing aide/config.yaml but it doesn't seem to work, can you help me?

**Comment by thesofakillers** [comment]
For running GPT-4o-mini through the standard OpenAI API (so, without changing the base url), you should be able to just add a key to AIDE's config.yaml, similar to what we have for gpt-4o and just swapping the agent.code.model to be 'gpt-4o-mini' (with the appropriate snapshot tag ideally:
https://github.com/openai/mle-bench/blob/51ec2b6789a5df0f902537e5b066dd0f6b8a6c2f/agents/aide/config.yaml#L20-L29

We dont support changing the base url out of the box in this repo. You're gonna have to enable that AIDE-side, probably by forking https://github.com/thesofakillers/aideml and making edits there to how the backends work:

https://github.com/thesofakillers/aideml/blob/d4a77cf3ca11e0f70749052b2701003e32bc245a/aide/backend/__init__.py#L8-L25
