### ISSUE TITLE
Detecting Insults in Social Commentary competition

### ISSUE THREAD

**Issue by MohammadrezaPourreza** [openai/mle-bench#24]
Hi,

Thank you for providing comprehensive documentation on how to use MLE-Bench.

While preparing the datasets, I encountered an issue with the "Detecting Insults in Social Commentary" competition. It appears there is no option to accept the competition rules, which prevents me from preparing this specific dataset.

Could you please advise on how to proceed?

**Comment by thesofakillers** [comment]
This is a duplicate of https://github.com/openai/mle-bench/issues/14. TLDR that comp has a different UX for accepting rules for some reason. See [this comment](https://github.com/openai/mle-bench/issues/14#issuecomment-2425714537).
