### ISSUE TITLE
add MLE-Agent support and test it using MLE-bench

### ISSUE THREAD

**Issue by HuaizhengZhang** [openai/mle-bench#4]
Thanks for the great work!!!

We develop an MLE-agent, which includes a `mle kaggle` command.

https://github.com/MLSysOps/MLE-agent?tab=readme-ov-file

We plan to test the MLE-agent with your MLE-bench and provide the evaluation results.

cc @huangyz0918

![image](https://github.com/user-attachments/assets/9b77eaad-4cee-4fd8-8371-d6caa20cfab8)

**Comment by ojaffe** [comment]
Exciting! Good luck MLE-agent

**Comment by danesherbs** [comment]
Closing this since it's a TODO on the MLSysOps/MLE-agent repo :)
