### ISSUE TITLE
Why 82 datasets are in `./mlebench/compositions` folder?

### ISSUE THREAD

**Issue by JK-SHIN-PG** [openai/mle-bench#5]
Hello, 

Thanks for the great work!

I noticed that seven datasets listed in `./mlebench/compositions` were not mentioned in the paper. Could you please confirm whether this indicates that the dataset has been extended?

**Comment by james-aung** [comment]
Thanks for the question. There are 7 competitions in the dev split beyond the 75 main competitions.

https://github.com/openai/mle-bench/blob/main/experiments/splits/dev.txt
